cleanup tests
git-svn-id: svn+ssh://svn.cern.ch/reps/hepmc/trunk@151 4525493e-7705-40b1-a816-d608a930855b

diff --git a/test/testMass.sh.in b/test/testMass.sh.in
--- a/test/testMass.sh.in
+++ b/test/testMass.sh.in
@@ -1,22 +1,30 @@
 #! /bin/sh
 # @configure_input@
 
+# want to see this output
 ./testMass@EXEEXT@
 
 OS=`uname`
 case "$OS" in
 CYGWIN*)
-  sed 's/e+0/e+/g'  testMass1.dat  | \
+  cmd1=`sed 's/e+0/e+/g'  testMass1.dat  | \
      sed 's/e-0/e-/g'  -  | \
-	@DIFF_Q@ - @srcdir@/testMass1.dat
-  @DIFF_Q@ testMass2.dat testMass1.dat
-  ;;
-Darwin*)
-  # MacOSX fix
-  @DIFF_Q@ testMass1.dat @srcdir@/testMass1.dat
-  @DIFF_Q@ testMass2.dat testMass1.dat
+	@DIFF_Q@ - @srcdir@/testMass1.dat`
   ;;
 *)
-  @DIFF_Q@ testMass1.dat @srcdir@/testMass1.dat
-  @DIFF_Q@ testMass2.dat testMass1.dat
+  cmd1=`@DIFF_Q@ testMass1.dat @srcdir@/testMass1.dat`
 esac
+
+if [ -n "$cmd1" ]
+then
+  echo $cmd1
+  exit 1;
+fi
+
+if ( ! `@DIFF_Q@ testMass2.dat testMass1.dat` )
+then
+  echo "comparison of testMass2.dat failed"
+  exit 1;
+fi
+
+exit 0;
