improve test scripts
git-svn-id: svn+ssh://svn.cern.ch/reps/hepmc/branches/HEPMC_02_01_branch@162 4525493e-7705-40b1-a816-d608a930855b

diff --git a/test/testMass.sh.in b/test/testMass.sh.in
--- a/test/testMass.sh.in
+++ b/test/testMass.sh.in
@@ -6,17 +6,24 @@
 OS=`uname`
 case "$OS" in
 CYGWIN*)
-  sed 's/e+0/e+/g'  testHepMCExtended.dat  | \
+  cmd1=`sed 's/e+0/e+/g'  testHepMCExtended.dat  | \
      sed 's/e-0/e-/g'  -  | \
-	@DIFF_Q@ - @srcdir@/testHepMCExtended.dat
-  @DIFF_Q@ testMass.dat testHepMCExtended.dat
-  ;;
-Darwin*)
-  # MacOSX fix
-  @DIFF_Q@ testHepMCExtended.dat @srcdir@/testHepMCExtended.dat
-  @DIFF_Q@ testMass.dat testHepMCExtended.dat
+	@DIFF_Q@ - @srcdir@/testHepMCExtended.dat`
   ;;
 *)
-  @DIFF_Q@ testHepMCExtended.dat @srcdir@/testHepMCExtended.dat
-  @DIFF_Q@ testMass.dat testHepMCExtended.dat
+  cmd1=`@DIFF_Q@ testHepMCExtended.dat @srcdir@/testHepMCExtended.dat`
 esac
+
+if [ -n "$cmd1" ]
+then
+  echo $cmd1
+  exit 1;
+fi
+
+if ( ! `@DIFF_Q@ testMass.dat testHepMCExtended.dat` )
+then
+  echo "comparison of testMass.dat failed"
+  exit 1;
+fi
+
+exit 0;
